# @package _group_

training_model:
  visualize_each_iters: 1000

losses:
  l1:
    weight: 1.0
  perceptual:
    weight: 1.0
  adversarial:
    weight: 1.0
  feature_matching:
    weight: 1.0
  resnet_pl:
    weight: 1.0
    weights_path: ${location.loss_models}

defaults:
  - location: defect_dataset_local
  - data: defect_dataset_test
  - generator: ffc_resnet_075
  - discriminator: pix2pixhd_nlayer
  - optimizers: default_optimizers
  - visualizer: default_visualizer
  - evaluator: default_evaluator
  - trainer: any_gpu_ddp
  - hydra: overrides