data_root_dir: /home/max/Datasets/defects_dataset
out_root_dir: /home/max/thesis/MaskGAN-controllable-object-inpainting/experiments
tb_dir: /home/max/thesis/MaskGAN-controllable-object-inpainting/experiments/tb_logs
pretrained_models: /home/ubuntu/thesis/MaskGAN-controllable-object-inpainting/models
loss_models: /home/ubuntu/thesis/MaskGAN-controllable-object-inpainting/models_loss