conf_name: Segmentation_severstal_test
run_name: ${conf_name}_${now:%d-%m-%Y_%H-%M-%S}

# training variables
checkpoint: null # path to the checkpoint file to load

epochs: 20
batch_size: 4
num_workers: 4
prefetch: 4

val_interval: 300 # validation interval in steps (batches)

device: cuda:0 # device to use for training
amp: True # enable automatic mixed precision

################################################
distributed: False # Do not touch distributed not implemented in Segmentation yet, variable still necessary for the dataloader
################################################

enable_wandb: True # enable wandb logging, if False no logging will be performed on the cloud
log_img_interval: 100 # steps interval between each output visualization
log_weights_interval: 100 # steps interval between each weights visualization
checkpoint_interval: 400 # steps interval between each checkpoint


defaults:
  - location: default_locations
  - data: severstal_dataset
  - model: unet
  - optimizers: default_optimizers
  - losses: default_losses
  - logger: default_logger
  - evaluator: default_evaluator
  - hydra: overrides