# @package _group_

conf_name: ${hydra:job.config_name}
run_name: ${hydra:job.config_name}_${now:%d-%m-%Y_%H-%M-%S}

# training variables
checkpoint: null
start_iter: 0
max_iter: 800000

batch_size: 8 # batch size for each training process
num_workers: 4 # dataloader workers

################################################
distributed: false # enable distributed training
################################################

visualize_each_iters: 1000

concat_mask: true
store_discr_outputs_for_vis: true


wandb:
  project: COIGAN
  entity: deep_learning_team
  mode: online

defaults:
  - location: default_locations
  - data: severstal_dataset
  - generator: ffc_resnet_075
  - discriminator: swagan_discriminator
  - optimizers: default_optimizers
  - losses: default_losses
  - visualizer: default_visualizer
  - evaluator: default_evaluator
  - trainer: any_gpu_ddp
  - hydra: overrides