# @package _group_

conf_name: COIGAN_severstal_test
run_name: ${conf_name}_${now:%d-%m-%Y_%H-%M-%S}

# training variables
checkpoint: null # path to the checkpoint file to load
start_iter: 0
max_iter: 800000

batch_size: 8 # batch size for each training process
num_workers: 6 # dataloader workers

gen_steps: 1 # define how many steps to train the generator before give the turn to the discriminator
disc_steps: 1 # define how many steps to train the discriminator before give the turn to the generator

use_ema: False # use exponential moving average for the generator

mask_base_img: False # If true zero out the base image where the concat masks are 1s, for the input_base_img and for the generator output

# input noise masks parameters
input_masks_noise_std: 0.05
input_masks_noise_mean: 0.5

################################################
distributed: True # enable distributed training
################################################

enable_wandb: True # enable wandb logging, if False no logging will be performed on the cloud
log_img_interval: 500 # steps interval between each output visualization
log_weights_interval: 500 # steps interval between each weights visualization
checkpoint_interval: 10000 # steps interval between each checkpoint


# logging other options
log_shapes_and_defects: false # enable the logging of input shapes and defects during the images logging


defaults:
  - location: default_locations
  - data: severstal_dataset
  - generator: ffc_resnet_075
  - discriminator: swagan_discriminator # pix2pixhd_nlayer or swagan_discriminator
  - optimizers: default_optimizers
  - losses: default_losses
  - logger: default_logger
  - evaluator: default_evaluator
  - hydra: overrides