# @package _group_

conf_name: COIGAN_severstal_test
run_name: ${conf_name}_${now:%d-%m-%Y_%H-%M-%S}

# training variables
checkpoint: null # path to the checkpoint file to load
start_iter: 0
max_iter: 800000

batch_size: 2 # batch size for each training process
num_workers: 4 # dataloader workers

gen_steps: 1 # define how many steps to train the generator before give the turn to the discriminator
disc_steps: 1 # define how many steps to train the discriminator before give the turn to the generator

################################################
distributed: false # enable distributed training
################################################

enable_wandb: false # enable wandb logging, if False no logging will be performed on the cloud
log_img_interval: 1000 # steps interval between each output visualization
checkpoint_interval: 10000 # steps interval between each checkpoint

concat_mask: true
store_discr_outputs_for_vis: true

defaults:
  - location: default_locations
  - data: severstal_dataset
  - generator: ffc_resnet_075
  - discriminator: swagan_discriminator
  - optimizers: default_optimizers
  - losses: default_losses
  - logger: default_logger
  - evaluator: default_evaluator
  - trainer: any_gpu_ddp
  - hydra: overrides