# @package _group_

conf_name: ${hydra:job.config_name}
run_name: ${hydra:job.config_name}_${now:%d-%m-%Y_%H-%M-%S}

training_model:
  kind: default
  visualize_each_iters: 1000
  concat_mask: true
  store_discr_outputs_for_vis: true

losses:
  l1:
    weight_missing: 0
    weight_known: 10
  perceptual:
    weight: 0
  adversarial:
    kind: r1
    weight: 10
    gp_coef: 0.001
    mask_as_fake_target: true
    allow_scale_mask: true
  feature_matching:
    weight: 100
  resnet_pl:
    weight: 30
    weights_path: ${env:TORCH_HOME}

wandb:
  project: COIGAN
  entity: deep_learning_team

defaults:
  - location: defect_dataset_local
  - data: defect_dataset_test
  - generator: ffc_resnet_075
  - discriminator: pix2pixhd_nlayer
  - optimizers: default_optimizers
  - visualizer: default_visualizer
  - evaluator: default_evaluator
  - trainer: any_gpu_ddp
  - hydra: overrides