data_root_dir: ${data.dataset_location}
out_root_dir: /home/max/thesis/COIGAN-controllable-object-inpainting/experiments

checkpoint_dir: ${hydra:run.dir}/checkpoints

pretrained_models: /home/ubuntu/thesis/COIGAN-controllable-object-inpainting/models
loss_models: /home/ubuntu/thesis/COIGAN-controllable-object-inpainting/models_loss