
######################################
### Loss manager parameters


######################################
### Generator losses parameters
generator_losses:
  reduction: sum # mean, sum

  l1:
    weight: 5
    
  adversarial:
    weight: 15

  feature_matching:
    weight: 10
    n_layers: 4 # number of layers to use for feature matching (starting from the last one)

  resnet_pl:
    weight: 5
    weights_path: ${location.loss_models}

# genrator regularitions
generator_reg:
  g_reg_every: 4 # n steps between 2 generator updarte regularizations
  path_lenght:
    weight: 5
    decay: 0.01

######################################
### Discriminator losses parameters
discriminator_losses:
  logistic:
    weight: 5

# discriminator regularitions
discriminator_reg: # TODO sistema i parametri
  d_reg_every: 16 # n steps between 2 discriminator updarte regularizations
  r1:
    weight: 10